//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mining_Application.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoint
    {
        public int ID { get; set; }
        public string PointName { get; set; }
        public string Capacity { get; set; }
        public int FieldID { get; set; }
    
        public virtual Field Field { get; set; }
    }
}
