//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People_application.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPeopleEntities : DbContext
    {
        public DBPeopleEntities()
            : base("name=DBPeopleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankNames> BankNames { get; set; }
        public virtual DbSet<Human> Human { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
