//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People_application.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public int ID { get; set; }
        public byte[] HumanImg { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int Age { get; set; }
        public int PassportID { get; set; }
    
        public virtual Passport Passport { get; set; }
    }
}
