//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Show_application.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoppDBEntities : DbContext
    {
        public CoppDBEntities()
            : base("name=CoppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COPP> COPP { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Specifications> Specifications { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
