//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Show_application.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int ID { get; set; }
        public byte[] ImageRoom { get; set; }
        public string NameOfRoom { get; set; }
        public int NumberOfPK { get; set; }
        public int SpecificationsID { get; set; }
    
        public virtual Specifications Specifications { get; set; }
    }
}
