//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_application.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int ID { get; set; }
        public string RouteNumber { get; set; }
        public string Distance { get; set; }
        public string DepPoint { get; set; }
        public string ArrPoint { get; set; }
        public int PlaneID { get; set; }
        public int ParamID { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual PlaneParameters PlaneParameters { get; set; }
    }
}
